# -*- coding: utf-8 -*-
from tkinter import ttk, messagebox
from src.core.database import get_session
from core.models import CariHesap
                class CariModule(ttk.Frame):
                                                                                                                                def __init__(
                                                                                                                                    self, parent):
                                                                                                                                                                                                                                                                super().__init__(parent)
                                                                                                                                                                                                                                                                self.pack(
                                                                                                                                                                                                                                                                    fill=tk.BOTH, expand=True)
                                                                                                                                                                                                                                                                self.create_widgets()
                                                                                                                                                                                                                                                                self.list_cari_hesaplar()
                                                                                                                                                                                                                def create_widgets(self):
                                                                                                                                                                                                                                                                # GiriÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¦İ¦Ãƒâ€š¸ formu
                                                                                                                                                                                                                                                                input_frame = ttk.LabelFrame(self, text="Cari Hesap Bilgileri")
                                                                                                                                                                                                                                                                input_frame.pack(fill=tk.X, padx=10, pady=10)
                                                                                                                                                                                                                                                                                                                                                                                                                # Grid yapÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±landÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±rma
                                                                                                                                                                                                                                                                input_frame.columnconfigure(1, weight=1)
                                                                                                                                                                                                                                                                input_frame.columnconfigure(3, weight=1)
                                                                                                                                                                                                                                                                                                                                                                                                                # Kodu
                                                                                                                                                                                                                                                                ttk.Label(input_frame, text="Cari Kodu:").grid(row=0, column=0, padx=5, pady=5, sticky=tk.W)
                                                                                                                                                                                                                                                                self.kod_entry = ttk.Entry(input_frame)
                                                                                                                                                                                                                                                                self.kod_entry.grid(row=0, column=1, padx=5, pady=5, sticky=tk.EW)
                                                                                                                                                                                                                                                                                                                                                                                                                # ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢İ¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œnvan
                                                                                                                                                                                                                                                                ttk.Label(input_frame, text="ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢İ¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œnvan:").grid(row=0, column=2, padx=5, pady=5, sticky=tk.W)
                                                                                                                                                                                                                                                                self.unvan_entry = ttk.Entry(input_frame, width=30)
                                                                                                                                                                                                                                                                self.unvan_entry.grid(row=0, column=3, padx=5, pady=5, sticky=tk.EW)
                                                                                                                                                                                                                                                                                                                                                                                                                # Adres
                                                                                                                                                                                                                                                                ttk.Label(input_frame, text="Adres:").grid(row=1, column=0, padx=5, pady=5, sticky=tk.W)
                                                                                                                                                                                                                                                                self.adres_entry = ttk.Entry(input_frame, width=50)
                                                                                                                                                                                                                                                                self.adres_entry.grid(row=1, column=1, columnspan=3, padx=5, pady=5, sticky=tk.EW)
                                                                                                                                                                                                                                                                                                                                                                                                                # Telefon
                                                                                                                                                                                                                                                                ttk.Label(input_frame, text="Telefon:").grid(row=2, column=0, padx=5, pady=5, sticky=tk.W)
                                                                                                                                                                                                                                                                self.telefon_entry = ttk.Entry(input_frame)
                                                                                                                                                                                                                                                                self.telefon_entry.grid(row=2, column=1, padx=5, pady=5, sticky=tk.EW)
                                                                                                                                                                                                                                                                                                                                                                                                                # Vergi Dairesi
                                                                                                                                                                                                                                                                ttk.Label(input_frame, text="Vergi Dairesi:").grid(row=2, column=2, padx=5, pady=5, sticky=tk.W)
                                                                                                                                                                                                                                                                self.vergi_dairesi_entry = ttk.Entry(input_frame)
                                                                                                                                                                                                                                                                self.vergi_dairesi_entry.grid(row=2, column=3, padx=5, pady=5, sticky=tk.EW)
                                                                                                                                                                                                                                                                                                                                                                                                                # Vergi No
                                                                                                                                                                                                                                                                ttk.Label(input_frame, text="Vergi No:").grid(row=3, column=0, padx=5, pady=5, sticky=tk.W)
                                                                                                                                                                                                                                                                self.vergi_no_entry = ttk.Entry(input_frame)
                                                                                                                                                                                                                                                                self.vergi_no_entry.grid(row=3, column=1, padx=5, pady=5, sticky=tk.EW)
                                                                                                                                                                                                                                                                                                                                                                                                                # Butonlar
                                                                                                                                                                                                                                                                btn_frame = ttk.Frame(input_frame)
                                                                                                                                                                                                                                                                btn_frame.grid(row=4, column=0, columnspan=4, pady=10)
                                                                                                                                                                                                                                                                                                                                                                                                                ttk.Button(btn_frame, text="Yeni", command=self.yeni_cari).pack(side=tk.LEFT, padx=5)
                                                                                                                                                                                                                                                                ttk.Button(btn_frame, text="Kaydet", command=self.kaydet).pack(side=tk.LEFT, padx=5)
                                                                                                                                                                                                                                                                ttk.Button(btn_frame, text="Sil", command=self.sil).pack(side=tk.LEFT, padx=5)
                                                                                                                                                                                                                                                                ttk.Button(btn_frame, text="Temizle", command=self.yeni_cari).pack(side=tk.LEFT, padx=5)
                                                                                                                                                                                                                                                                                                                                                                                                                # Treeview
                                                                                                                                                                                                                                                                list_frame = ttk.LabelFrame(self, text="Cari Hesap Listesi")
                                                                                                                                                                                                                                                                list_frame.pack(fill=tk.BOTH, expand=True, padx=10, pady=10)
                                                                                                                                                                                                                                                                                                                                                                                                                columns = ("kod", "unvan", "telefon", "vergi_dairesi", "vergi_no")
                                                                                                                                                                                                                                                                self.tree = ttk.Treeview(list_frame, columns=columns, show="headings")
                                                                                                                                                                                                                                                                                                                                                                                                                # SÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š¼tun baÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¦İ¦Ãƒâ€š¸lÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±klarÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±
                                                                                                                                                                                                                                                                self.tree.heading("kod", text="Cari Kodu")
                                                                                                                                                                                                                                                                self.tree.heading("unvan", text="ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢İ¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œnvan")
                                                                                                                                                                                                                                                                self.tree.heading("telefon", text="Telefon")
                                                                                                                                                                                                                                                                self.tree.heading("vergi_dairesi", text="Vergi Dairesi")
                                                                                                                                                                                                                                                                self.tree.heading("vergi_no", text="Vergi No")
                                                                                                                                                                                                                                                                                                                                                                                                                # SÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š¼tun geniÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¦İ¦Ãƒâ€š¸likleri
                                                                                                                                                                                                                                                                self.tree.column("kod", width=100)
                                                                                                                                                                                                                                                                self.tree.column("unvan", width=200)
                                                                                                                                                                                                                                                                self.tree.column("telefon", width=120)
                                                                                                                                                                                                                                                                self.tree.column("vergi_dairesi", width=150)
                                                                                                                                                                                                                                                                self.tree.column("vergi_no", width=120)
                                                                                                                                                                                                                                                                                                                                                                                                                self.tree.pack(fill=tk.BOTH, expand=True)
                                                                                                                                                                                                                                                                                                                                                                                                                # Scrollbar
                                                                                                                                                                                                                                                                scrollbar = ttk.Scrollbar(list_frame, orient="vertical", command=self.tree.yview)
                                                                                                                                                                                                                                                                self.tree.configure(yscrollcommand=scrollbar.set)
                                                                                                                                                                                                                                                                scrollbar.pack(side="right", fill="y")
                                                                                                                                                                                                                                                                                                                                                                                                                self.tree.bind("<<TreeviewSelect>>", self.on_select)
                                                                                                                                                                                                                                                                                                                                                                                                                # Arama ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š§ubuÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾İ¦Ãƒâ€š¸u
                                                                                                                                                                                                                                                                search_frame = ttk.Frame(list_frame)
                                                                                                                                                                                                                                                                search_frame.pack(fill=tk.X, padx=5, pady=5)
                                                                                                                                                                                                                                                                                                                                                                                                                ttk.Label(search_frame, text="Ara:").pack(side=tk.LEFT)
                                                                                                                                                                                                                                                                self.search_entry = ttk.Entry(search_frame)
                                                                                                                                                                                                                                                                self.search_entry.pack(side=tk.LEFT, padx=5, fill=tk.X, expand=True)
                                                                                                                                                                                                                                                                self.search_entry.bind("<KeyRelease>", self.filter_cari)
                                                                                                                                                                                                                                                                                def yeni_cari(self):
                                                                                                                                                                                                                                                                self.kod_entry.delete(0, tk.END)
                                                                                                                                                                                                                                                                self.unvan_entry.delete(0, tk.END)
                                                                                                                                                                                                                                                                self.adres_entry.delete(0, tk.END)
                                                                                                                                                                                                                                                                self.telefon_entry.delete(0, tk.END)
                                                                                                                                                                                                                                                                self.vergi_dairesi_entry.delete(0, tk.END)
                                                                                                                                                                                                                                                                self.vergi_no_entry.delete(0, tk.END)
                                                                                                                                                                                                                                                                self.tree.selection_remove(self.tree.selection())
                                                                                                                                                                                                                def kaydet(self):
                                                                                                                                                                                                                                                                kod = self.kod_entry.get().strip()
                                                                                                                                                                                                                                                                unvan = self.unvan_entry.get().strip()
                                                                                                                                                                                                                                                                adres = self.adres_entry.get().strip()
                                                                                                                                                                                                                                                                telefon = self.telefon_entry.get().strip()
                                                                                                                                                                                                                                                                vergi_dairesi = self.vergi_dairesi_entry.get().strip()
                                                                                                                                                                                                                                                                vergi_no = self.vergi_no_entry.get().strip()
                                                                                                                                                                                                                                                                                                                                                                                                                if not kod or not unvan:
                                                                                                                                                                                                                                                                                                                                                                                                messagebox.showerror("Hata", "Cari kodu ve ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š¼nvan zorunludur!")
                                                                                                                                                                                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                                                                                                                                                                                                session = get_session("main.db")
                                                                                                                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                # EÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾İ¦Ãƒâ€š¸er varsa gÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š¼ncelle, yoksa ekle
                                                                                                                                                                                                                                                                                                                                                                                                cari = session.query(CariHesap).filter_by(kod=kod).first()
                                                                                                                                                                                                                                                                                                                                                                                                if cari:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cari.unvan = unvan
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cari.adres = adres
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cari.telefon = telefon
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cari.vergi_dairesi = vergi_dairesi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cari.vergi_no = vergi_no
                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cari = CariHesap(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                kod=kod,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                unvan=unvan,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                adres=adres,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                telefon=telefon,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                vergi_dairesi=vergi_dairesi,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                vergi_no=vergi_no
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                session.add(cari)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                session.commit()
                                                                                                                                                                                                                                                                                                                                                                                                self.list_cari_hesaplar()
                                                                                                                                                                                                                                                                                                                                                                                                self.yeni_cari()
                                                                                                                                                                                                                                                                                                                                                                                                messagebox.showinfo("BaÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¦İ¦Ãƒâ€š¸arÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±lÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±", "Cari hesap kaydedildi")
                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                messagebox.showerror("Hata", f"KayÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±t sÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±rasÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±nda hata oluÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¦İ¦Ãƒâ€š¸tu: {str(e)}")
                                                                                                                                                                                                                                                                finally:
                                                                                                                                                                                                                                                                                                                                                                                                session.close()
                                                                                                                                                                                                                def sil(self):
                                                                                                                                                                                                                                                                selected = self.tree.selection()
                                                                                                                                                                                                                                                                if not selected:
                                                                                                                                                                                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                                                                                                                                                                                                kod = self.tree.item(selected[0], "values")[0]
                                                                                                                                                                                                                                                                                                                                                                                                                if messagebox.askyesno("Onay", f"{kod} kodlu cari hesabÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š± silmek istediÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾İ¦Ãƒâ€š¸inize emin misiniz?"):
                                                                                                                                                                                                                                                                                                                                                                                                session = get_session("main.db")
                                                                                                                                                                                                                                                                                                                                                                                                cari = session.query(CariHesap).filter_by(kod=kod).first()
                                                                                                                                                                                                                                                                                                                                                                                                if cari:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                session.delete(cari)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                session.commit()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.list_cari_hesaplar()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.yeni_cari()
                                                                                                                                                                                                                                                                                                                                                                                                session.close()
                                                                                                                                                                                                                def list_cari_hesaplar(self):
                                                                                                                                                                                                                                                                # ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’¢ÃƒÂ¢Ã¢â‚¬Å¡¬ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œnce mevcut listeyi temizle
                                                                                                                                                                                                                                                                for item in self.tree.get_children():
                                                                                                                                                                                                                                                                                                                                                                                                self.tree.delete(item)
                                                                                                                                                                                                                                                                                                                                                                                                                session = get_session("main.db")
                                                                                                                                                                                                                                                                cariler = session.query(CariHesap).order_by(CariHesap.kod).all()
                                                                                                                                                                                                                                                                session.close()
                                                                                                                                                                                                                                                                                                                                                                                                                for cari in cariler:
                                                                                                                                                                                                                                                                                                                                                                                                self.tree.insert("", tk.END, values=(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cari.kod,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cari.unvan,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cari.telefon or "",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cari.vergi_dairesi or "",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cari.vergi_no or ""
                                                                                                                                                                                                                                                                                                                                                                                                ))
                                                                                                                                                                                                                def on_select(self, event):
                                                                                                                                                                                                                                                                selected = self.tree.selection()
                                                                                                                                                                                                                                                                if not selected:
                                                                                                                                                                                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                                                                                                                                                                                                values = self.tree.item(selected[0], "values")
                                                                                                                                                                                                                                                                self.yeni_cari()
                                                                                                                                                                                                                                                                                                                                                                                                                self.kod_entry.insert(0, values[0])
                                                                                                                                                                                                                                                                self.unvan_entry.insert(0, values[1])
                                                                                                                                                                                                                                                                                                                                                                                                                # DiÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾İ¦Ãƒâ€š¸er alanlar iÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š§in kontrol
                                                                                                                                                                                                                                                                if len(values) > 2: self.telefon_entry.insert(0, values[2])
                                                                                                                                                                                                                                                                if len(values) > 3: self.vergi_dairesi_entry.insert(0, values[3])
                                                                                                                                                                                                                                                                if len(values) > 4: self.vergi_no_entry.insert(0, values[4])
                                                                                                                                                                                                                def filter_cari(self, event):
                                                                                                                                                                                                                                                                query = self.search_entry.get().lower()
                                                                                                                                                                                                                                                                                                                                                                                                                for child in self.tree.get_children():
                                                                                                                                                                                                                                                                                                                                                                                                values = self.tree.item(child, "values")
                                                                                                                                                                                                                                                                                                                                                                                                if any(query in str(value).lower() for value in values):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.tree.item(child, tags=('visible',))
                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.tree.item(child, tags=('hidden',))
                                                                                                                                                                                                                                                                                                                                                                                                                # GÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š¶rÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š¼nÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š¼rlÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š¼ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾İ¦Ãƒâ€š¸ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š¼ gÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š¼ncelle
                                                                                                                                                                                                                                                                self.tree.tag_configure('visible', display='')
                                                                                                                                                                                                                                                                self.tree.tag_configure('hidden', display='none')






