# -*- coding: utf-8 -*-
from core.models import CariAccount, CariTransaction
                class CariManager:
                                                                                                                                @staticmethod
                                                                                                                                def create_account(
                                                                                                                                    firm_id, account_type, account_code, account_name, **kwargs):
                                                                                                                                                                                                                                                                session = get_session()
                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                new_account = CariAccount(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                firm_id=firm_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                account_type=account_type,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                account_code=account_code,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                account_name=account_name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                **kwargs
                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                session.add(
                                                                                                                                                                                                                                                                                                                                                                                                    new_account)
                                                                                                                                                                                                                                                                                                                                                                                                session.commit()
                                                                                                                                                                                                                                                                                                                                                                                                return new_account
                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                session.rollback()
                                                                                                                                                                                                                                                                                                                                                                                                raise e
                                                                                                                                                                                                                                                                finally:
                                                                                                                                                                                                                                                                                                                                                                                                session.close()
                                                                                                                                                @staticmethod
                                                                                                                                def add_transaction(account_id, transaction_type, amount, description):
                                                                                                                                                                                                                                                                session = get_session()
                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                # ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š°ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¦İ¦Ãƒâ€š¸lemi ekle
                                                                                                                                                                                                                                                                                                                                                                                                new_transaction = CariTransaction(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                account_id=account_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                transaction_type=transaction_type,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                amount=amount,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                description=description
                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                session.add(new_transaction)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Bakiyeyi gÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š¼ncelle
                                                                                                                                                                                                                                                                                                                                                                                                account = session.query(CariAccount).get(account_id)
                                                                                                                                                                                                                                                                                                                                                                                                if transaction_type == "BorÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š§":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                account.balance += amount
                                                                                                                                                                                                                                                                                                                                                                                                elif transaction_type == "Alacak":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                account.balance -= amount
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                session.commit()
                                                                                                                                                                                                                                                                                                                                                                                                return new_transaction
                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                session.rollback()
                                                                                                                                                                                                                                                                                                                                                                                                raise e
                                                                                                                                                                                                                                                                finally:
                                                                                                                                                                                                                                                                                                                                                                                                session.close()
                                                                                                                                                @staticmethod
                                                                                                                                def get_account_balance(account_id):
                                                                                                                                                                                                                                                                session = get_session()
                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                account = session.query(CariAccount).get(account_id)
                                                                                                                                                                                                                                                                                                                                                                                                return account.balance
                                                                                                                                                                                                                                                                finally:
                                                                                                                                                                                                                                                                                                                                                                                                session.close()
                                                                                                                                                @staticmethod
                                                                                                                                def search_accounts(firm_id, search_term=None, account_type=None):
                                                                                                                                                                                                                                                                session = get_session()
                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                query = session.query(CariAccount).filter_by(firm_id=firm_id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if search_term:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                query = query.filter(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (CariAccount.account_name.contains(search_term)) |
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (CariAccount.account_code.contains(search_term)) |
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (CariAccount.tax_id.contains(search_term))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if account_type:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                query = query.filter_by(account_type=account_type)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return query.all()
                                                                                                                                                                                                                                                                finally:
                                                                                                                                                                                                                                                                                                                                                                                                session.close()




