# -*- coding: utf-8 -*-
from tkinter import ttk
from core.database import get_session
from core.models import CariHesap
                class CariModule(tk.Frame):
                                                                                                                                def __init__(
                                                                                                                                    self, parent):
                                                                                                                                                                                                                                                                super().__init__(parent, bg="#ecf0f1")
                                                                                                                                                                                                                                                                self.parent = parent
                                                                                                                                                                                                                                                                self.create_widgets()
                                                                                                                                                                                                                                                                self.load_data()
                                                                                                                                                                                                                def create_widgets(self):
                                                                                                                                                                                                                                                                # AraÃƒÆ’Ã†â€™Ãƒâ€š§ ÃƒÆ’Ã†â€™Ãƒâ€š§ubuÃƒÆ’Ã¢â‚¬Å¾Ãƒâ€¦¸u - Daha belirgin
                                                                                                                                                                                                                                                                toolbar = tk.Frame(self, bg="#3498db", height=50)
                                                                                                                                                                                                                                                                toolbar.pack(fill=tk.X, padx=5, pady=5)
                                                                                                                                                                                                                                                                                                                                                                                                                # Butonlar - Daha bÃƒÆ’Ã†â€™Ãƒâ€š¼yÃƒÆ’Ã†â€™Ãƒâ€š¼k ve ikonlu
                                                                                                                                                                                                                                                                buttons = [
                                                                                                                                                                                                                                                                                                                                                                                                {"text": "ÃƒÆ’¢Ãƒâ€¦¾ÃƒÂ¢Ã¢â€šÂ¬¢ Yeni", "command": self.new_cari},
                                                                                                                                                                                                                                                                                                                                                                                                {"text": "ÃƒÆ’¢Ãƒâ€¦Ã¢â‚¬Å“Ãƒâ€šÃƒÆ’¯Ãƒâ€š¸Ãƒâ€š DÃƒÆ’Ã†â€™Ãƒâ€š¼zenle", "command": self.edit_cari},
                                                                                                                                                                                                                                                                                                                                                                                                {"text": "ÃƒÆ’°Ãƒâ€¦¸ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬ÂÃƒÂ¢Ã¢â€šÂ¬Ã‹Å“ÃƒÆ’¯Ãƒâ€š¸Ãƒâ€š Sil", "command": self.delete_cari},
                                                                                                                                                                                                                                                                                                                                                                                                {"text": "ÃƒÆ’°Ãƒâ€¦¸ÃƒÂ¢Ã¢â€šÂ¬ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ Yenile", "command": self.load_data}
                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                                                                                                                                for btn in buttons:
                                                                                                                                                                                                                                                                                                                                                                                                b = tk.Button(toolbar, text=btn["text"], command=btn["command"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bg="#2c3e50", fg="white", font=("Arial", 10),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padx=10, pady=5, relief=tk.FLAT)
                                                                                                                                                                                                                                                                                                                                                                                                b.pack(side=tk.LEFT, padx=5)
                                                                                                                                                                                                                                                                                                                                                                                                                # Arama kutusu - Daha bÃƒÆ’Ã†â€™Ãƒâ€š¼yÃƒÆ’Ã†â€™Ãƒâ€š¼k
                                                                                                                                                                                                                                                                search_frame = tk.Frame(toolbar, bg="#3498db")
                                                                                                                                                                                                                                                                search_frame.pack(side=tk.RIGHT, padx=10)
                                                                                                                                                                                                                                                                                                                                                                                                                ttk.Label(search_frame, text="ÃƒÆ’°Ãƒâ€¦¸ÃƒÂ¢Ã¢â€šÂ¬Ãƒâ€š Ara:", background="#3498db",
                                                                                                                                                                                                                                                                                foreground="white").pack(side=tk.LEFT)
                                                                                                                                                                                                                                                                                                                                                                                                                self.search_var = tk.StringVar()
                                                                                                                                                                                                                                                                search_entry = ttk.Entry(search_frame, textvariable=self.search_var, width=30)
                                                                                                                                                                                                                                                                search_entry.pack(side=tk.LEFT, padx=5)
                                                                                                                                                                                                                                                                                                                                                                                                                search_btn = tk.Button(search_frame, text="Ara", command=self.search_cari,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bg="#e67e22", fg="white", font=("Arial", 9),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padx=5, pady=2)
                                                                                                                                                                                                                                                                search_btn.pack(side=tk.LEFT)
                                                                                                                                                                                                                                                                                                                                                                                                                # Liste - Daha bÃƒÆ’Ã†â€™Ãƒâ€š¼yÃƒÆ’Ã†â€™Ãƒâ€š¼k ve dÃƒÆ’Ã†â€™Ãƒâ€š¼zenli
                                                                                                                                                                                                                                                                list_frame = tk.Frame(self, bg="#ecf0f1")
                                                                                                                                                                                                                                                                list_frame.pack(fill=tk.BOTH, expand=True, padx=10, pady=10)
                                                                                                                                                                                                                                                                                                                                                                                                                columns = ("id", "unvan", "kodu", "tip", "bakiye")
                                                                                                                                                                                                                                                                self.tree = ttk.Treeview(list_frame, columns=columns, show="headings", selectmode="browse")
                                                                                                                                                                                                                                                                                                                                                                                                                # Kolon baİ¦Ãƒâ€¦¸lıkları
                                                                                                                                                                                                                                                                self.tree.heading("id", text="ID")
                                                                                                                                                                                                                                                                self.tree.heading("unvan", text="ÃƒÆ’Ã†â€™Ãƒâ€¦Ã¢â‚¬Å“nvan")
                                                                                                                                                                                                                                                                self.tree.heading("kodu", text="Kodu")
                                                                                                                                                                                                                                                                self.tree.heading("tip", text="Tip")
                                                                                                                                                                                                                                                                self.tree.heading("bakiye", text="Bakiye")
                                                                                                                                                                                                                                                                                                                                                                                                                # Kolon geniİ¦Ãƒâ€¦¸likleri
                                                                                                                                                                                                                                                                self.tree.column("id", width=50, anchor="center")
                                                                                                                                                                                                                                                                self.tree.column("unvan", width=300)
                                                                                                                                                                                                                                                                self.tree.column("kodu", width=100, anchor="center")
                                                                                                                                                                                                                                                                self.tree.column("tip", width=100, anchor="center")
                                                                                                                                                                                                                                                                self.tree.column("bakiye", width=100, anchor="center")
                                                                                                                                                                                                                                                                                                                                                                                                                # Scrollbar
                                                                                                                                                                                                                                                                scrollbar = ttk.Scrollbar(list_frame, orient=tk.VERTICAL, command=self.tree.yview)
                                                                                                                                                                                                                                                                self.tree.configure(yscroll=scrollbar.set)
                                                                                                                                                                                                                                                                                                                                                                                                                self.tree.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
                                                                                                                                                                                                                                                                scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
                                                                                                                                                                                                                                                                                                                                                                                                                # ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¡ift tıklama ile dÃƒÆ’Ã†â€™Ãƒâ€š¼zenleme
                                                                                                                                                                                                                                                                self.tree.bind("<Double-1>", self.on_double_click)
                                                                                                                                                                                                                def load_data(self):
                                                                                                                                                                                                                                                                # ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“nceki verileri temizle
                                                                                                                                                                                                                                                                for i in self.tree.get_children():
                                                                                                                                                                                                                                                                                                                                                                                                self.tree.delete(i)
                                                                                                                                                                                                                                                                                                                                                                                                                # Veritabanından cari hesapları yÃƒÆ’Ã†â€™Ãƒâ€š¼kle
                                                                                                                                                                                                                                                                session = next(get_session())
                                                                                                                                                                                                                                                                cari_list = session.query(CariHesap).all()
                                                                                                                                                                                                                                                                                                                                                                                                                for cari in cari_list:
                                                                                                                                                                                                                                                                                                                                                                                                self.tree.insert("", tk.END, values=(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cari.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cari.unvan,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cari.kodu,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cari.tip,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                f"{cari.bakiye:,.2f} ÃƒÆ’¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šº"
                                                                                                                                                                                                                                                                                                                                                                                                ))
                                                                                                                                                                                                                def search_cari(self):
                                                                                                                                                                                                                                                                # Arama fonksiyonu
                                                                                                                                                                                                                                                                pass
                                                                                                                                                                                                                def on_double_click(self, event):
                                                                                                                                                                                                                                                                # ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¡ift tıklama ile dÃƒÆ’Ã†â€™Ãƒâ€š¼zenleme
                                                                                                                                                                                                                                                                self.edit_cari()
                                                                                                                                                                                                                def new_cari(self):
                                                                                                                                                                                                                                                                # Yeni cari ekleme fonksiyonu
                                                                                                                                                                                                                                                                print("Yeni cari ekleme iİ¦Ãƒâ€¦¸lemi")
                                                                                                                                                                                                                def edit_cari(self):
                                                                                                                                                                                                                                                                # Cari dÃƒÆ’Ã†â€™Ãƒâ€š¼zenleme fonksiyonu
                                                                                                                                                                                                                                                                selected = self.tree.selection()
                                                                                                                                                                                                                                                                if selected:
                                                                                                                                                                                                                                                                                                                                                                                                item = self.tree.item(selected[0])
                                                                                                                                                                                                                                                                                                                                                                                                print(f"DÃƒÆ’Ã†â€™Ãƒâ€š¼zenle: {item['values']}")
                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                messagebox.showwarning("Uyarı", "LÃƒÆ’Ã†â€™Ãƒâ€š¼tfen bir cari hesap seÃƒÆ’Ã†â€™Ãƒâ€š§in")
                                                                                                                                                                                                                def delete_cari(self):
                                                                                                                                                                                                                                                                # Cari silme fonksiyonu
                                                                                                                                                                                                                                                                selected = self.tree.selection()
                                                                                                                                                                                                                                                                if selected:
                                                                                                                                                                                                                                                                                                                                                                                                item = self.tree.item(selected[0])
                                                                                                                                                                                                                                                                                                                                                                                                print(f"Sil: {item['values']}")
                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                messagebox.showwarning("Uyarı", "LÃƒÆ’Ã†â€™Ãƒâ€š¼tfen bir cari hesap seÃƒÆ’Ã†â€™Ãƒâ€š§in")




