# -*- coding: utf-8 -*-
from tkinter import ttk, messagebox
from core.database import get_session
from core.models import Firm
from modules.auth.manager import create_user, authenticate
                class LoginFrame(tk.Frame):
                                                                                                                                def __init__(
                                                                                                                                    self, parent, on_success_callback):
                                                                                                                                                                                                                                                                super().__init__(parent)
                                                                                                                                                                                                                                                                self.on_success = on_success_callback
                                                                                                                                                                                                                                                                self.create_widgets()
                                                                                                                                                                                                                                                                self.load_firmalar()
                                                                                                                                                                                                                                                                                def create_widgets(
                                                                                                                                                                                                                                                                                    self):
                                                                                                                                                                                                                                                                ttk.Label(self, text="Firma SeÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š§in:").pack(
                                                                                                                                                                                                                                                                    pady=5)
                                                                                                                                                                                                                                                                self.firma_combo = ttk.Combobox(
                                                                                                                                                                                                                                                                    self, state="readonly")
                                                                                                                                                                                                                                                                self.firma_combo.pack(
                                                                                                                                                                                                                                                                    pady=5)
                                                                                                                                                                                                                                                                                                                                                                                                                ttk.Label(self, text="KullanÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±cÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š± AdÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±:").pack(
                                                                                                                                                                                                                                                                                                                                                                                                                    pady=5)
                                                                                                                                                                                                                                                                self.username_entry = ttk.Entry(
                                                                                                                                                                                                                                                                    self)
                                                                                                                                                                                                                                                                self.username_entry.pack(
                                                                                                                                                                                                                                                                    pady=5)
                                                                                                                                                                                                                                                                                                                                                                                                                ttk.Label(self, text="ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¦İ¦Ãƒâ€š¾ifre:").pack(
                                                                                                                                                                                                                                                                                                                                                                                                                    pady=5)
                                                                                                                                                                                                                                                                self.password_entry = ttk.Entry(
                                                                                                                                                                                                                                                                    self, show="*")
                                                                                                                                                                                                                                                                self.password_entry.pack(
                                                                                                                                                                                                                                                                    pady=5)
                                                                                                                                                                                                                                                                                                                                                                                                                ttk.Button(self, text="GiriÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¦İ¦Ãƒâ€š¸ Yap", command=self.authenticate).pack(
                                                                                                                                                                                                                                                                                                                                                                                                                    pady=20)
                                                                                                                                                                                                                                                                                def load_firmalar(self):
                                                                                                                                                                                                                                                                session = get_session()
                                                                                                                                                                                                                                                                firmalar = session.query(Firm).all()
                                                                                                                                                                                                                                                                self.firma_combo['values'] = [firma.name for firma in firmalar]
                                                                                                                                                                                                                                                                if firmalar:
                                                                                                                                                                                                                                                                                                                                                                                                self.firma_combo.current(0)
                                                                                                                                                                                                                                                                session.close()
                                                                                                                                                                                                                def authenticate(self):
                                                                                                                                                                                                                                                                selected_firma = self.firma_combo.get()
                                                                                                                                                                                                                                                                username = self.username_entry.get()
                                                                                                                                                                                                                                                                password = self.password_entry.get()
                                                                                                                                                                                                                                                                                                                                                                                                                if not selected_firma or not username or not password:
                                                                                                                                                                                                                                                                                                                                                                                                messagebox.showerror("Hata", "LÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š¼tfen tÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š¼m alanlarÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š± doldurun.")
                                                                                                                                                                                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                session = get_session()
                                                                                                                                                                                                                                                                firma = session.query(Firm).filter_by(name=selected_firma).first()
                                                                                                                                                                                                                                                                session.close()
                                                                                                                                                                                                                                                                                                                                                                                                                if not firma:
                                                                                                                                                                                                                                                                                                                                                                                                messagebox.showerror("Hata", "GeÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š§ersiz firma seÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š§imi.")
                                                                                                                                                                                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                user = authenticate(username, password, firma.id)
                                                                                                                                                                                                                                                                if user:
                                                                                                                                                                                                                                                                                                                                                                                                self.on_success(user, firma)
                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                messagebox.showerror("Hata", "GeÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š§ersiz kullanÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±cÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š± adÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š± veya ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¦İ¦Ãƒâ€š¸ifre.")
                                class FirmRegistrationDialog(tk.Toplevel):
                                                                                                                                def __init__(self, parent, on_success):
                                                                                                                                                                                                                                                                super().__init__(parent)
                                                                                                                                                                                                                                                                self.title("Firma KaydÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±")
                                                                                                                                                                                                                                                                self.geometry("400x350")
                                                                                                                                                                                                                                                                self.on_success = on_success
                                                                                                                                                                                                                                                                self.create_widgets()
                                                                                                                                                                                                                                                                                def create_widgets(self):
                                                                                                                                                                                                                                                                ttk.Label(self, text="Firma AdÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±:").pack(pady=5)
                                                                                                                                                                                                                                                                self.firma_adi = ttk.Entry(self)
                                                                                                                                                                                                                                                                self.firma_adi.pack(pady=5)
                                                                                                                                                                                                                                                                                                                                                                                                                ttk.Label(self, text="Vergi Dairesi:").pack(pady=5)
                                                                                                                                                                                                                                                                self.vergi_dairesi = ttk.Entry(self)
                                                                                                                                                                                                                                                                self.vergi_dairesi.pack(pady=5)
                                                                                                                                                                                                                                                                                                                                                                                                                ttk.Label(self, text="Vergi NumarasÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±:").pack(pady=5)
                                                                                                                                                                                                                                                                self.vergi_no = ttk.Entry(self)
                                                                                                                                                                                                                                                                self.vergi_no.pack(pady=5)
                                                                                                                                                                                                                                                                                                                                                                                                                ttk.Label(self, text="Adres:").pack(pady=5)
                                                                                                                                                                                                                                                                self.adres = ttk.Entry(self)
                                                                                                                                                                                                                                                                self.adres.pack(pady=5)
                                                                                                                                                                                                                                                                                                                                                                                                                ttk.Label(self, text="Telefon:").pack(pady=5)
                                                                                                                                                                                                                                                                self.telefon = ttk.Entry(self)
                                                                                                                                                                                                                                                                self.telefon.pack(pady=5)
                                                                                                                                                                                                                                                                                                                                                                                                                ttk.Label(self, text="E-posta:").pack(pady=5)
                                                                                                                                                                                                                                                                self.email = ttk.Entry(self)
                                                                                                                                                                                                                                                                self.email.pack(pady=5)
                                                                                                                                                                                                                                                                                                                                                                                                                ttk.Button(self, text="Kaydet", command=self.save).pack(pady=15)
                                                                                                                                                                                                                                                                                def save(self):
                                                                                                                                                                                                                                                                firma_data = {
                                                                                                                                                                                                                                                                                                                                                                                                'name': self.firma_adi.get(),
                                                                                                                                                                                                                                                                                                                                                                                                'tax_office': self.vergi_dairesi.get(),
                                                                                                                                                                                                                                                                                                                                                                                                'tax_number': self.vergi_no.get(),
                                                                                                                                                                                                                                                                                                                                                                                                'address': self.adres.get(),
                                                                                                                                                                                                                                                                                                                                                                                                'phone': self.telefon.get(),
                                                                                                                                                                                                                                                                                                                                                                                                'email': self.email.get(),
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                if not all(firma_data.values()):
                                                                                                                                                                                                                                                                                                                                                                                                messagebox.showerror("Hata", "LÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š¼tfen tÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š¼m alanlarÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š± doldurun.")
                                                                                                                                                                                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                                                                                                                                                                                                session = get_session()
                                                                                                                                                                                                                                                                new_firma = Firm(**firma_data)
                                                                                                                                                                                                                                                                session.add(new_firma)
                                                                                                                                                                                                                                                                session.commit()
                                                                                                                                                                                                                                                                session.refresh(new_firma)
                                                                                                                                                                                                                                                                session.close()
                                                                                                                                                                                                                                                                                                                                                                                                                self.on_success(new_firma)
                                                                                                                                                                                                                                                                self.destroy()
                                class AdminRegistrationDialog(tk.Toplevel):
                                                                                                                                def __init__(self, parent, firma, on_success):
                                                                                                                                                                                                                                                                super().__init__(parent)
                                                                                                                                                                                                                                                                self.title("Admin KullanÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±cÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š± OluÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¦İ¦Ãƒâ€š¸tur")
                                                                                                                                                                                                                                                                self.geometry("400x300")
                                                                                                                                                                                                                                                                self.firma = firma
                                                                                                                                                                                                                                                                self.on_success = on_success
                                                                                                                                                                                                                                                                self.create_widgets()
                                                                                                                                                                                                                                                                                def create_widgets(self):
                                                                                                                                                                                                                                                                ttk.Label(self, text="Admin KullanÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±cÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š± AdÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±:").pack(pady=5)
                                                                                                                                                                                                                                                                self.username = ttk.Entry(self)
                                                                                                                                                                                                                                                                self.username.pack(pady=5)
                                                                                                                                                                                                                                                                                                                                                                                                                ttk.Label(self, text="ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¦İ¦Ãƒâ€š¾ifre:").pack(pady=5)
                                                                                                                                                                                                                                                                self.password = ttk.Entry(self, show="*")
                                                                                                                                                                                                                                                                self.password.pack(pady=5)
                                                                                                                                                                                                                                                                                                                                                                                                                ttk.Label(self, text="ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¦İ¦Ãƒâ€š¾ifre (Tekrar):").pack(pady=5)
                                                                                                                                                                                                                                                                self.password_again = ttk.Entry(self, show="*")
                                                                                                                                                                                                                                                                self.password_again.pack(pady=5)
                                                                                                                                                                                                                                                                                                                                                                                                                ttk.Label(self, text="E-posta:").pack(pady=5)
                                                                                                                                                                                                                                                                self.email = ttk.Entry(self)
                                                                                                                                                                                                                                                                self.email.pack(pady=5)
                                                                                                                                                                                                                                                                                                                                                                                                                ttk.Button(self, text="OluÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¦İ¦Ãƒâ€š¸tur", command=self.create_admin).pack(pady=15)
                                                                                                                                                                                                                                                                                def create_admin(self):
                                                                                                                                                                                                                                                                username = self.username.get()
                                                                                                                                                                                                                                                                password = self.password.get()
                                                                                                                                                                                                                                                                password_again = self.password_again.get()
                                                                                                                                                                                                                                                                email = self.email.get()
                                                                                                                                                                                                                                                                                                                                                                                                                if password != password_again:
                                                                                                                                                                                                                                                                                                                                                                                                messagebox.showerror("Hata", "ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¦İ¦Ãƒâ€š¾ifreler eÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¦İ¦Ãƒâ€š¸leÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¦İ¦Ãƒâ€š¸miyor.")
                                                                                                                                                                                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if not username or not password:
                                                                                                                                                                                                                                                                                                                                                                                                messagebox.showerror("Hata", "KullanÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±cÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š± adÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š± ve ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¦İ¦Ãƒâ€š¸ifre boÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¦İ¦Ãƒâ€š¸ olamaz.")
                                                                                                                                                                                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                user = create_user(username, password, "admin", email, self.firma.id)
                                                                                                                                                                                                                                                                if user:
                                                                                                                                                                                                                                                                                                                                                                                                self.on_success(self.firma, user)
                                                                                                                                                                                                                                                                                                                                                                                                self.destroy()
                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                messagebox.showerror("Hata", "KullanÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±cÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š± oluÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¦İ¦Ãƒâ€š¸turulamadÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±.")
                



