# -*- coding: utf-8 -*-
from src.core.database import get_session
from core.models import User
                class AuthManager:
                                                                                                                                def __init__(
                                                                                                                                    self, db_path):
                                                                                                                                                                                                                                                                self.db_path = db_path
                                                                                                                                                                                                                                                                                def create_user(
                                                                                                                                                                                                                                                                                    self, username, password, role, email="", firm_id=None):
                                                                                                                                                                                                                                                                session = get_session()
                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                existing_user = session.query(User).filter_by(
                                                                                                                                                                                                                                                                                                                                                                                                    username=username, firm_id=firm_id).first()
                                                                                                                                                                                                                                                                                                                                                                                                if existing_user:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return None
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                hashed_password = generate_password_hash(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    password)
                                                                                                                                                                                                                                                                                                                                                                                                new_user = User(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                username=username,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                password_hash=hashed_password,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                role=role,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                email=email,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                firm_id=firm_id
                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                session.add(
                                                                                                                                                                                                                                                                                                                                                                                                    new_user)
                                                                                                                                                                                                                                                                                                                                                                                                session.commit()
                                                                                                                                                                                                                                                                                                                                                                                                session.refresh(
                                                                                                                                                                                                                                                                                                                                                                                                    new_user)
                                                                                                                                                                                                                                                                                                                                                                                                return new_user
                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                print(
                                                                                                                                                                                                                                                                                                                                                                                                    f"KullanÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±cÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š± oluÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬¦İ¦Ãƒâ€š¸turma hatasÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€š±: {str(e)}")
                                                                                                                                                                                                                                                                                                                                                                                                return None
                                                                                                                                                                                                                                                                finally:
                                                                                                                                                                                                                                                                                                                                                                                                session.close()
                                                                                                                                                                                                                                                                                                                                                def authenticate(self, username, password, firm_id=None):
                                                                                                                                                                                                                                                                session = get_session()
                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                user = session.query(User).filter_by(username=username, firm_id=firm_id).first()
                                                                                                                                                                                                                                                                                                                                                                                                if user and check_password_hash(user.password_hash, password):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return user
                                                                                                                                                                                                                                                                                                                                                                                                return None
                                                                                                                                                                                                                                                                finally:
                                                                                                                                                                                                                                                                                                                                                                                                session.close()






